// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PuzzleService.Data;

#nullable disable

namespace PuzzleService.Migrations
{
    [DbContext(typeof(PuzzleDbContext))]
    partial class PuzzleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PuzzleService.Models.PuzzleEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("HiddenPart")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hidden_part");

                    b.Property<string>("OpenPart")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("open_part");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("StoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("story_id");

                    b.HasKey("Id");

                    b.ToTable("puzzles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
