// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: puzzle.proto

package puzzle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRandomPuzzleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Опционально — исключить уже виденные пользователем данетки
	ExcludeIds    []string `protobuf:"bytes,1,rep,name=exclude_ids,json=excludeIds,proto3" json:"exclude_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRandomPuzzleRequest) Reset() {
	*x = GetRandomPuzzleRequest{}
	mi := &file_puzzle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRandomPuzzleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomPuzzleRequest) ProtoMessage() {}

func (x *GetRandomPuzzleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_puzzle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomPuzzleRequest.ProtoReflect.Descriptor instead.
func (*GetRandomPuzzleRequest) Descriptor() ([]byte, []int) {
	return file_puzzle_proto_rawDescGZIP(), []int{0}
}

func (x *GetRandomPuzzleRequest) GetExcludeIds() []string {
	if x != nil {
		return x.ExcludeIds
	}
	return nil
}

type GetPuzzleByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PuzzleId      string                 `protobuf:"bytes,1,opt,name=puzzle_id,json=puzzleId,proto3" json:"puzzle_id,omitempty"` // UUID данетки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPuzzleByIdRequest) Reset() {
	*x = GetPuzzleByIdRequest{}
	mi := &file_puzzle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPuzzleByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPuzzleByIdRequest) ProtoMessage() {}

func (x *GetPuzzleByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_puzzle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPuzzleByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPuzzleByIdRequest) Descriptor() ([]byte, []int) {
	return file_puzzle_proto_rawDescGZIP(), []int{1}
}

func (x *GetPuzzleByIdRequest) GetPuzzleId() string {
	if x != nil {
		return x.PuzzleId
	}
	return ""
}

type ListPuzzlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // номер страницы, начиная с 1
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // количество на странице, макс 50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPuzzlesRequest) Reset() {
	*x = ListPuzzlesRequest{}
	mi := &file_puzzle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPuzzlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPuzzlesRequest) ProtoMessage() {}

func (x *ListPuzzlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_puzzle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPuzzlesRequest.ProtoReflect.Descriptor instead.
func (*ListPuzzlesRequest) Descriptor() ([]byte, []int) {
	return file_puzzle_proto_rawDescGZIP(), []int{2}
}

func (x *ListPuzzlesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPuzzlesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListPuzzlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Puzzles       []*PuzzleResponse      `protobuf:"bytes,1,rep,name=puzzles,proto3" json:"puzzles,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // общее количество данеток в БД
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPuzzlesResponse) Reset() {
	*x = ListPuzzlesResponse{}
	mi := &file_puzzle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPuzzlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPuzzlesResponse) ProtoMessage() {}

func (x *ListPuzzlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_puzzle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPuzzlesResponse.ProtoReflect.Descriptor instead.
func (*ListPuzzlesResponse) Descriptor() ([]byte, []int) {
	return file_puzzle_proto_rawDescGZIP(), []int{3}
}

func (x *ListPuzzlesResponse) GetPuzzles() []*PuzzleResponse {
	if x != nil {
		return x.Puzzles
	}
	return nil
}

func (x *ListPuzzlesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPuzzlesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type PuzzleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PuzzleId      string                 `protobuf:"bytes,1,opt,name=puzzle_id,json=puzzleId,proto3" json:"puzzle_id,omitempty"`     // UUID
	OpenPart      string                 `protobuf:"bytes,2,opt,name=open_part,json=openPart,proto3" json:"open_part,omitempty"`     // текст загадки — то что видит игрок
	SourceUrl     string                 `protobuf:"bytes,3,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`  // источник истории
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp создания
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PuzzleResponse) Reset() {
	*x = PuzzleResponse{}
	mi := &file_puzzle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PuzzleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PuzzleResponse) ProtoMessage() {}

func (x *PuzzleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_puzzle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PuzzleResponse.ProtoReflect.Descriptor instead.
func (*PuzzleResponse) Descriptor() ([]byte, []int) {
	return file_puzzle_proto_rawDescGZIP(), []int{4}
}

func (x *PuzzleResponse) GetPuzzleId() string {
	if x != nil {
		return x.PuzzleId
	}
	return ""
}

func (x *PuzzleResponse) GetOpenPart() string {
	if x != nil {
		return x.OpenPart
	}
	return ""
}

func (x *PuzzleResponse) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *PuzzleResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type SavePuzzleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenPart      string                 `protobuf:"bytes,1,opt,name=open_part,json=openPart,proto3" json:"open_part,omitempty"`       // открытая часть данетки
	HiddenPart    string                 `protobuf:"bytes,2,opt,name=hidden_part,json=hiddenPart,proto3" json:"hidden_part,omitempty"` // закрытая часть — хранится в БД, не отдаётся клиенту
	SourceUrl     string                 `protobuf:"bytes,3,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`    // URL источника откуда взята история
	StoryId       string                 `protobuf:"bytes,4,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`          // ID истории из MongoDB (для Saga — трассировка)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavePuzzleRequest) Reset() {
	*x = SavePuzzleRequest{}
	mi := &file_puzzle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavePuzzleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePuzzleRequest) ProtoMessage() {}

func (x *SavePuzzleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_puzzle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePuzzleRequest.ProtoReflect.Descriptor instead.
func (*SavePuzzleRequest) Descriptor() ([]byte, []int) {
	return file_puzzle_proto_rawDescGZIP(), []int{5}
}

func (x *SavePuzzleRequest) GetOpenPart() string {
	if x != nil {
		return x.OpenPart
	}
	return ""
}

func (x *SavePuzzleRequest) GetHiddenPart() string {
	if x != nil {
		return x.HiddenPart
	}
	return ""
}

func (x *SavePuzzleRequest) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *SavePuzzleRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

type SavePuzzleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PuzzleId      string                 `protobuf:"bytes,1,opt,name=puzzle_id,json=puzzleId,proto3" json:"puzzle_id,omitempty"` // UUID созданной данетки
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavePuzzleResponse) Reset() {
	*x = SavePuzzleResponse{}
	mi := &file_puzzle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavePuzzleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePuzzleResponse) ProtoMessage() {}

func (x *SavePuzzleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_puzzle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePuzzleResponse.ProtoReflect.Descriptor instead.
func (*SavePuzzleResponse) Descriptor() ([]byte, []int) {
	return file_puzzle_proto_rawDescGZIP(), []int{6}
}

func (x *SavePuzzleResponse) GetPuzzleId() string {
	if x != nil {
		return x.PuzzleId
	}
	return ""
}

func (x *SavePuzzleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_puzzle_proto protoreflect.FileDescriptor

const file_puzzle_proto_rawDesc = "" +
	"\n" +
	"\fpuzzle.proto\x12\x06puzzle\"9\n" +
	"\x16GetRandomPuzzleRequest\x12\x1f\n" +
	"\vexclude_ids\x18\x01 \x03(\tR\n" +
	"excludeIds\"3\n" +
	"\x14GetPuzzleByIdRequest\x12\x1b\n" +
	"\tpuzzle_id\x18\x01 \x01(\tR\bpuzzleId\"E\n" +
	"\x12ListPuzzlesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"q\n" +
	"\x13ListPuzzlesResponse\x120\n" +
	"\apuzzles\x18\x01 \x03(\v2\x16.puzzle.PuzzleResponseR\apuzzles\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\"\x88\x01\n" +
	"\x0ePuzzleResponse\x12\x1b\n" +
	"\tpuzzle_id\x18\x01 \x01(\tR\bpuzzleId\x12\x1b\n" +
	"\topen_part\x18\x02 \x01(\tR\bopenPart\x12\x1d\n" +
	"\n" +
	"source_url\x18\x03 \x01(\tR\tsourceUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"\x8b\x01\n" +
	"\x11SavePuzzleRequest\x12\x1b\n" +
	"\topen_part\x18\x01 \x01(\tR\bopenPart\x12\x1f\n" +
	"\vhidden_part\x18\x02 \x01(\tR\n" +
	"hiddenPart\x12\x1d\n" +
	"\n" +
	"source_url\x18\x03 \x01(\tR\tsourceUrl\x12\x19\n" +
	"\bstory_id\x18\x04 \x01(\tR\astoryId\"K\n" +
	"\x12SavePuzzleResponse\x12\x1b\n" +
	"\tpuzzle_id\x18\x01 \x01(\tR\bpuzzleId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\xae\x02\n" +
	"\rPuzzleService\x12I\n" +
	"\x0fGetRandomPuzzle\x12\x1e.puzzle.GetRandomPuzzleRequest\x1a\x16.puzzle.PuzzleResponse\x12E\n" +
	"\rGetPuzzleById\x12\x1c.puzzle.GetPuzzleByIdRequest\x1a\x16.puzzle.PuzzleResponse\x12F\n" +
	"\vListPuzzles\x12\x1a.puzzle.ListPuzzlesRequest\x1a\x1b.puzzle.ListPuzzlesResponse\x12C\n" +
	"\n" +
	"SavePuzzle\x12\x19.puzzle.SavePuzzleRequest\x1a\x1a.puzzle.SavePuzzleResponseB@Z#github.com/danetka/contracts/puzzle\xaa\x02\x18Danetka.Contracts.Puzzleb\x06proto3"

var (
	file_puzzle_proto_rawDescOnce sync.Once
	file_puzzle_proto_rawDescData []byte
)

func file_puzzle_proto_rawDescGZIP() []byte {
	file_puzzle_proto_rawDescOnce.Do(func() {
		file_puzzle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_puzzle_proto_rawDesc), len(file_puzzle_proto_rawDesc)))
	})
	return file_puzzle_proto_rawDescData
}

var file_puzzle_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_puzzle_proto_goTypes = []any{
	(*GetRandomPuzzleRequest)(nil), // 0: puzzle.GetRandomPuzzleRequest
	(*GetPuzzleByIdRequest)(nil),   // 1: puzzle.GetPuzzleByIdRequest
	(*ListPuzzlesRequest)(nil),     // 2: puzzle.ListPuzzlesRequest
	(*ListPuzzlesResponse)(nil),    // 3: puzzle.ListPuzzlesResponse
	(*PuzzleResponse)(nil),         // 4: puzzle.PuzzleResponse
	(*SavePuzzleRequest)(nil),      // 5: puzzle.SavePuzzleRequest
	(*SavePuzzleResponse)(nil),     // 6: puzzle.SavePuzzleResponse
}
var file_puzzle_proto_depIdxs = []int32{
	4, // 0: puzzle.ListPuzzlesResponse.puzzles:type_name -> puzzle.PuzzleResponse
	0, // 1: puzzle.PuzzleService.GetRandomPuzzle:input_type -> puzzle.GetRandomPuzzleRequest
	1, // 2: puzzle.PuzzleService.GetPuzzleById:input_type -> puzzle.GetPuzzleByIdRequest
	2, // 3: puzzle.PuzzleService.ListPuzzles:input_type -> puzzle.ListPuzzlesRequest
	5, // 4: puzzle.PuzzleService.SavePuzzle:input_type -> puzzle.SavePuzzleRequest
	4, // 5: puzzle.PuzzleService.GetRandomPuzzle:output_type -> puzzle.PuzzleResponse
	4, // 6: puzzle.PuzzleService.GetPuzzleById:output_type -> puzzle.PuzzleResponse
	3, // 7: puzzle.PuzzleService.ListPuzzles:output_type -> puzzle.ListPuzzlesResponse
	6, // 8: puzzle.PuzzleService.SavePuzzle:output_type -> puzzle.SavePuzzleResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_puzzle_proto_init() }
func file_puzzle_proto_init() {
	if File_puzzle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_puzzle_proto_rawDesc), len(file_puzzle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_puzzle_proto_goTypes,
		DependencyIndexes: file_puzzle_proto_depIdxs,
		MessageInfos:      file_puzzle_proto_msgTypes,
	}.Build()
	File_puzzle_proto = out.File
	file_puzzle_proto_goTypes = nil
	file_puzzle_proto_depIdxs = nil
}
