// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: puzzle.proto

package puzzle

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PuzzleService_GetRandomPuzzle_FullMethodName = "/puzzle.PuzzleService/GetRandomPuzzle"
	PuzzleService_GetPuzzleById_FullMethodName   = "/puzzle.PuzzleService/GetPuzzleById"
	PuzzleService_ListPuzzles_FullMethodName     = "/puzzle.PuzzleService/ListPuzzles"
	PuzzleService_SavePuzzle_FullMethodName      = "/puzzle.PuzzleService/SavePuzzle"
)

// PuzzleServiceClient is the client API for PuzzleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PuzzleServiceClient interface {
	// Получить случайную данетку (для пользователя)
	GetRandomPuzzle(ctx context.Context, in *GetRandomPuzzleRequest, opts ...grpc.CallOption) (*PuzzleResponse, error)
	// Получить конкретную данетку по ID (для пользователя)
	GetPuzzleById(ctx context.Context, in *GetPuzzleByIdRequest, opts ...grpc.CallOption) (*PuzzleResponse, error)
	// Получить список данеток с пагинацией (для пользователя)
	ListPuzzles(ctx context.Context, in *ListPuzzlesRequest, opts ...grpc.CallOption) (*ListPuzzlesResponse, error)
	// Сохранить готовую данетку — только для AI Worker
	SavePuzzle(ctx context.Context, in *SavePuzzleRequest, opts ...grpc.CallOption) (*SavePuzzleResponse, error)
}

type puzzleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPuzzleServiceClient(cc grpc.ClientConnInterface) PuzzleServiceClient {
	return &puzzleServiceClient{cc}
}

func (c *puzzleServiceClient) GetRandomPuzzle(ctx context.Context, in *GetRandomPuzzleRequest, opts ...grpc.CallOption) (*PuzzleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PuzzleResponse)
	err := c.cc.Invoke(ctx, PuzzleService_GetRandomPuzzle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *puzzleServiceClient) GetPuzzleById(ctx context.Context, in *GetPuzzleByIdRequest, opts ...grpc.CallOption) (*PuzzleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PuzzleResponse)
	err := c.cc.Invoke(ctx, PuzzleService_GetPuzzleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *puzzleServiceClient) ListPuzzles(ctx context.Context, in *ListPuzzlesRequest, opts ...grpc.CallOption) (*ListPuzzlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPuzzlesResponse)
	err := c.cc.Invoke(ctx, PuzzleService_ListPuzzles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *puzzleServiceClient) SavePuzzle(ctx context.Context, in *SavePuzzleRequest, opts ...grpc.CallOption) (*SavePuzzleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SavePuzzleResponse)
	err := c.cc.Invoke(ctx, PuzzleService_SavePuzzle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PuzzleServiceServer is the server API for PuzzleService service.
// All implementations must embed UnimplementedPuzzleServiceServer
// for forward compatibility.
type PuzzleServiceServer interface {
	// Получить случайную данетку (для пользователя)
	GetRandomPuzzle(context.Context, *GetRandomPuzzleRequest) (*PuzzleResponse, error)
	// Получить конкретную данетку по ID (для пользователя)
	GetPuzzleById(context.Context, *GetPuzzleByIdRequest) (*PuzzleResponse, error)
	// Получить список данеток с пагинацией (для пользователя)
	ListPuzzles(context.Context, *ListPuzzlesRequest) (*ListPuzzlesResponse, error)
	// Сохранить готовую данетку — только для AI Worker
	SavePuzzle(context.Context, *SavePuzzleRequest) (*SavePuzzleResponse, error)
	mustEmbedUnimplementedPuzzleServiceServer()
}

// UnimplementedPuzzleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPuzzleServiceServer struct{}

func (UnimplementedPuzzleServiceServer) GetRandomPuzzle(context.Context, *GetRandomPuzzleRequest) (*PuzzleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRandomPuzzle not implemented")
}
func (UnimplementedPuzzleServiceServer) GetPuzzleById(context.Context, *GetPuzzleByIdRequest) (*PuzzleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPuzzleById not implemented")
}
func (UnimplementedPuzzleServiceServer) ListPuzzles(context.Context, *ListPuzzlesRequest) (*ListPuzzlesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPuzzles not implemented")
}
func (UnimplementedPuzzleServiceServer) SavePuzzle(context.Context, *SavePuzzleRequest) (*SavePuzzleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SavePuzzle not implemented")
}
func (UnimplementedPuzzleServiceServer) mustEmbedUnimplementedPuzzleServiceServer() {}
func (UnimplementedPuzzleServiceServer) testEmbeddedByValue()                       {}

// UnsafePuzzleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PuzzleServiceServer will
// result in compilation errors.
type UnsafePuzzleServiceServer interface {
	mustEmbedUnimplementedPuzzleServiceServer()
}

func RegisterPuzzleServiceServer(s grpc.ServiceRegistrar, srv PuzzleServiceServer) {
	// If the following call panics, it indicates UnimplementedPuzzleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PuzzleService_ServiceDesc, srv)
}

func _PuzzleService_GetRandomPuzzle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRandomPuzzleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PuzzleServiceServer).GetRandomPuzzle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PuzzleService_GetRandomPuzzle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PuzzleServiceServer).GetRandomPuzzle(ctx, req.(*GetRandomPuzzleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PuzzleService_GetPuzzleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPuzzleByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PuzzleServiceServer).GetPuzzleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PuzzleService_GetPuzzleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PuzzleServiceServer).GetPuzzleById(ctx, req.(*GetPuzzleByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PuzzleService_ListPuzzles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPuzzlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PuzzleServiceServer).ListPuzzles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PuzzleService_ListPuzzles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PuzzleServiceServer).ListPuzzles(ctx, req.(*ListPuzzlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PuzzleService_SavePuzzle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SavePuzzleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PuzzleServiceServer).SavePuzzle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PuzzleService_SavePuzzle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PuzzleServiceServer).SavePuzzle(ctx, req.(*SavePuzzleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PuzzleService_ServiceDesc is the grpc.ServiceDesc for PuzzleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PuzzleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "puzzle.PuzzleService",
	HandlerType: (*PuzzleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRandomPuzzle",
			Handler:    _PuzzleService_GetRandomPuzzle_Handler,
		},
		{
			MethodName: "GetPuzzleById",
			Handler:    _PuzzleService_GetPuzzleById_Handler,
		},
		{
			MethodName: "ListPuzzles",
			Handler:    _PuzzleService_ListPuzzles_Handler,
		},
		{
			MethodName: "SavePuzzle",
			Handler:    _PuzzleService_SavePuzzle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "puzzle.proto",
}
