# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_generated import parser_pb2 as parser__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in parser_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ParserServiceStub(object):
    """Parser gRPC service stub."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartParsing = channel.unary_unary(
                '/parser.ParserService/StartParsing',
                request_serializer=parser__pb2.StartParsingRequest.SerializeToString,
                response_deserializer=parser__pb2.StartParsingResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/parser.ParserService/GetStatus',
                request_serializer=parser__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=parser__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.ListJobs = channel.unary_unary(
                '/parser.ParserService/ListJobs',
                request_serializer=parser__pb2.ListJobsRequest.SerializeToString,
                response_deserializer=parser__pb2.ListJobsResponse.FromString,
                _registered_method=True)


class ParserServiceServicer(object):
    """Parser gRPC service interface."""

    def StartParsing(self, request, context):
        """Start parsing job."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get parsing job status."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
        """List parsing jobs."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartParsing': grpc.unary_unary_rpc_method_handler(
                    servicer.StartParsing,
                    request_deserializer=parser__pb2.StartParsingRequest.FromString,
                    response_serializer=parser__pb2.StartParsingResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=parser__pb2.GetStatusRequest.FromString,
                    response_serializer=parser__pb2.GetStatusResponse.SerializeToString,
            ),
            'ListJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJobs,
                    request_deserializer=parser__pb2.ListJobsRequest.FromString,
                    response_serializer=parser__pb2.ListJobsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'parser.ParserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('parser.ParserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ParserService(object):
    """Parser gRPC service client."""

    @staticmethod
    def StartParsing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parser.ParserService/StartParsing',
            parser__pb2.StartParsingRequest.SerializeToString,
            parser__pb2.StartParsingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parser.ParserService/GetStatus',
            parser__pb2.GetStatusRequest.SerializeToString,
            parser__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parser.ParserService/ListJobs',
            parser__pb2.ListJobsRequest.SerializeToString,
            parser__pb2.ListJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
